// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Project struct {
	ID          int64
	Name        string
	Description sql.NullString
	ParentID    sql.NullInt64
	PlannedFor  sql.NullTime
	StartAt     sql.NullTime
	DueAt       sql.NullTime
	CompletedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Task struct {
	ID          int64
	Name        string
	Description sql.NullString
	PlannedFor  sql.NullTime
	StartAt     sql.NullTime
	DueAt       sql.NullTime
	CompletedAt sql.NullTime
	ProjectID   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TimeEntry struct {
	ID        int64
	StartAt   time.Time
	EndAt     sql.NullTime
	TaskID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
