// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Project struct {
	ID          int64
	Name        string
	Description sql.NullString
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Task struct {
	ID          int64
	Name        string
	Description sql.NullString
	Status      string
	ProjectID   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TimeEntry struct {
	StartAt   time.Time
	EndAt     sql.NullTime
	TaskID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
