// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"
)

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks SET completed_at = IIF(completed_at IS NULL, DATE(), completed_at) WHERE id = ?
`

func (q *Queries) CompleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, name, description, planned_for, start_at, due_at, completed_at, project_id, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PlannedFor,
		&i.StartAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const scheduledTasks = `-- name: ScheduledTasks :many
WITH RECURSIVE rec_project_name(id, name, level) AS (
  SELECT id, name, 1 AS level FROM projects WHERE parent_id IS NULL
  UNION ALL
  SELECT
    projects.id,
    rec_project_name.name||' > '||projects.name,
    rec_project_name.level + 1
  FROM projects
  JOIN rec_project_name ON projects.parent_id = rec_project_name.id
)
SELECT tasks.id, tasks.name, project_id, planned_for, start_at, due_at, rec_project_name.name AS project_name, rec_project_name.level AS project_level
FROM tasks
JOIN rec_project_name ON tasks.project_id = rec_project_name.id
WHERE planned_for <= DATE() AND completed_at IS NULL ORDER BY planned_for, start_at NULLS LAST, due_at NULLS LAST
`

type ScheduledTasksRow struct {
	ID           int64
	Name         string
	ProjectID    int64
	PlannedFor   sql.NullTime
	StartAt      sql.NullTime
	DueAt        sql.NullTime
	ProjectName  string
	ProjectLevel int64
}

func (q *Queries) ScheduledTasks(ctx context.Context) ([]ScheduledTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, scheduledTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledTasksRow
	for rows.Next() {
		var i ScheduledTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectID,
			&i.PlannedFor,
			&i.StartAt,
			&i.DueAt,
			&i.ProjectName,
			&i.ProjectLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTask = `-- name: StartTask :exec
UPDATE tasks SET start_at = IIF(start_at IS NULL, DATE(), start_at) WHERE id = ?
`

func (q *Queries) StartTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, startTask, id)
	return err
}
